name: Maven CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup Java and Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven
          maven-version: 3.9.2
      
      - name: Build
        run: mvn -B -DskipTests clean package
      
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-app-jar
          path: target/my-app-1.0-SNAPSHOT.jar

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup Java and Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven
          maven-version: 3.9.2
      
      - name: Run Tests
        run: mvn verify
      
      - name: Publish Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/surefire-reports/*.xml

  deliver:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup Java and Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven
          maven-version: 3.9.2
      
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: my-app-jar
          path: target/
      
      - name: Deliver
        run: ./jenkins/scripts/deliver.sh
